headers = {"User-Agent": "milosfxc@gmail.com"}

pg_balance_sheet_columns = {'share_id': 'share_id',
                            'date': 'date',
                            'currency_id': 'currency_id',
                            'period': 'period',
                            'calendarYear': 'financial_year',
                            'totalAssets': 'assets',
                            'cashAndCashEquivalents': 'cash_and_cash_equivalents',
                            'shortTermInvestments': 'short_term_investments',
                            'cashAndShortTermInvestments': 'cash_and_short_term_investments',
                            'netReceivables': 'net_receivables',
                            'inventory': 'inventory',
                            'otherCurrentAssets': 'other_current_assets',
                            'totalCurrentAssets': 'current_assets',
                            'propertyPlantEquipmentNet': 'property_plant_equipment_net',
                            'goodwill': 'goodwill',
                            'intangibleAssets': 'intangible_assets',
                            'longTermInvestments': 'long_term_investments',
                            'taxAssets': 'tax_assets',
                            'otherNonCurrentAssets': 'other_non_current_assets',
                            'totalNonCurrentAssets': 'non_current_assets',
                            'accountPayables': 'account_payables',
                            'shortTermDebt': 'short_term_debt',
                            'otherCurrentLiabilities': 'other_current_liabilities',
                            'totalCurrentLiabilities': 'current_liabilities',
                            'longTermDebt': 'long_term_debt',
                            'otherNonCurrentLiabilities': 'other_non_current_liabilities',
                            'totalNonCurrentLiabilities': 'non_current_liabilities',
                            'totalDebt': 'debt',
                            'netDebt': 'net_debt',
                            'totalLiabilities': 'liabilities',
                            'preferredStock': 'preferred_stock_equity',
                            'commonStock': 'common_stock_equity',
                            'retainedEarnings': 'retained_earnings',
                            'minorityInterest': 'minority_interest',
                            'accumulatedOtherComprehensiveIncomeLoss': 'accumulated_other_comprehensive_income_loss',
                            'totalEquity': 'equity'}

pg_income_statement_columns = {'share_id': 'share_id',
                               'date': 'date',
                               'currency_id': 'currency_id',
                               'period': 'period',
                               'calendarYear': 'financial_year',
                               'acceptedDate': 'report_date',
                               'revenue': 'revenue',
                               'costOfRevenue': 'cost_of_revenue',
                               'grossProfit': 'gross_profit',
                               'researchAndDevelopmentExpenses': 'research_and_development_expenses',
                               'sellingGeneralAndAdministrativeExpenses': 'general_and_administrative_expenses',
                               'sellingAndMarketingExpenses': 'selling_and_marketing_expenses',
                               'otherExpenses': 'other_expenses',
                               'operatingExpenses': 'operating_expenses',
                               'interestIncome': 'interest_income_expense',
                               'incomeTaxExpense': 'tax_income_expense',
                               'depreciationAndAmortization': 'depreciation_and_amortization',
                               'ebitda': 'ebitda',
                               'incomeBeforeTax': 'ebit',
                               'operatingIncome': 'operating_income',
                               'netIncome': 'net_income',
                               'eps': 'eps',
                               'epsdiluted': 'diluted_eps'}

pg_cash_flow_columns = {'share_id': 'share_id',
                        'date': 'date',
                        'currency_id': 'currency_id',
                        'period': 'period',
                        'calendarYear': 'financial_year',
                        'freeCashFlow': 'free_cash_flow',
                        'operatingCashFlow': 'operating_cash_flow',
                        'netIncome': 'net_income',
                        'depreciationAndAmortization': 'depreciation_and_amortization',
                        'deferredIncomeTax': 'deferred_income_tax',
                        'stockBasedCompensation': 'stock_based_compensation',
                        'changeInWorkingCapital': 'change_working_capital',
                        'accountsReceivables': 'accounts_receivables',
                        'inventory': 'inventory',
                        'accountsPayables': 'accounts_payables',
                        'otherWorkingCapital': 'other_working_capital',
                        'otherNonCashItems': 'other_non_cash_items',
                        'netCashUsedForInvestingActivites': 'investing_cash_flow',
                        'investmentsInPropertyPlantAndEquipment': 'investments_ppe',
                        'acquisitionsNet': 'acquisitions_net',
                        'purchasesOfInvestments': 'purchases_of_investments',
                        'salesMaturitiesOfInvestments': 'sales_maturities_of_investments',
                        'otherInvestingActivites': 'other_investing_activities',
                        'netCashUsedProvidedByFinancingActivities': 'financing_cash_flow',
                        'debtRepayment': 'debt_repayment',
                        'commonStockIssued': 'common_stock_issued',
                        'commonStockRepurchased': 'common_stock_repurchased',
                        'dividendsPaid': 'dividends_paid',
                        'otherFinancingActivites': 'other_financing_activities',
                        'cashAtBeginningOfPeriod': 'cash_at_beginning_of_period',
                        'cashAtEndOfPeriod': 'cash_at_end_of_period',
                        'netChangeInCash': 'net_change_in_cash'}

pg_tables = {
    'balance_sheet': pg_balance_sheet_columns,
    'income_statement': pg_income_statement_columns,
    'cash_flow': pg_cash_flow_columns
}
