from utils import income_statement

balance_sheet_gaap = {
    # Banks
    'deposits': {'us-gaap:TimeDepositMaturitiesRollingYearTwo', 'us-gaap:NoninterestBearingDepositLiabilitiesDomestic', 'us-gaap:DepositsWholesale', 'us-gaap:TimeDepositMaturitiesRollingYearFive',
                 'us-gaap:DepositsForeign', 'us-gaap:DepositsRetail', 'us-gaap:InterestBearingDepositLiabilitiesDomestic', 'us-gaap:DemandDepositAccounts',
                 'us-gaap:DepositsNegotiableOrderOfWithdrawalNOW', 'us-gaap:DepositContractsLiabilities', 'us-gaap:DepositsSavingsDeposits', 'us-gaap:NoninterestBearingDepositLiabilities',
                 'us-gaap:TimeDepositMaturitiesRollingYearFour', 'us-gaap:NoninterestBearingDepositLiabilitiesForeign', 'us-gaap:TimeDepositMaturitiesAfterRollingYearFive',
                 'us-gaap:DepositsDomestic', 'us-gaap:InterestBearingDepositLiabilitiesForeign', 'us-gaap:InterestBearingDepositLiabilities', 'us-gaap:TimeDeposits',
                 'us-gaap:TimeDepositMaturitiesNextRollingTwelveMonths', 'us-gaap:TimeDepositMaturitiesAfterNextRollingTwelveMonths', 'us-gaap:TimeDepositMaturitiesRollingYearThree',
                 'us-gaap:DepositsMoneyMarketDepositsAndNegotiableOrderOfWithdrawalNOW', 'us-gaap:DepositsMoneyMarketDeposits', 'us-gaap:Deposits'},
    'investments_all': {'loc_FixturesAndEquipmentGross', 'us-gaap:LongTermInvestments', 'us-gaap:OtherRestrictedAssetsCurrent', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesWithinOneYearFairValue',
                    'us-gaap:MarketableSecurities', 'loc_MarketableSecuritiesCurrent', 'loc_RealEstateInvestmentPropertyNet', 'us-gaap:AdvancesToAffiliate', 'loc_MortgageLoanOnRealEstateNonincomeProducing',
                    'loc_SecuritiesHeldAsCollateralAtFairValue', 'us-gaap:DebtSecuritiesHeldToMaturityAllowanceForCreditLossCurrent', 'us-gaap:NotesAndLoansReceivableNetNoncurrent',
                    'us-gaap:MarketableSecuritiesNoncurrent', 'us-gaap:DebtSecuritiesCurrent', 'loc_HeldToMaturitySecurities', 'us-gaap:DebtSecuritiesNoncurrent', 'loc_RealEstateInvestmentPropertyAtCost',
                    'loc_AvailableForSaleSecuritiesDebtSecuritiesCurrent', 'us-gaap:TradingSecurities', 'loc_InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures', 'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesCurrent',
                    'us-gaap:TradingSecuritiesDebt', 'loc_AllowanceForLoanAndLeaseLossesRealEstate', 'loc_Investments', 'us-gaap:OtherLongTermInvestments', 'loc_SecuritiesBorrowed', 'us-gaap:ShortTermInvestments',
                    'loc_MarketableSecurities', 'loc_DevelopmentInProcess', 'us-gaap:CryptoAssetFairValueNoncurrent', 'us-gaap:RestrictedInvestmentsCurrent', 'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesSingleMaturityDateAmortizedCostBasis',
                    'loc_TenantImprovements', 'us-gaap:LifeInsuranceCorporateOrBankOwnedAmount', 'loc_AvailableForSaleSecuritiesDebtSecuritiesNoncurrent', 'us-gaap:NotesAndLoansReceivableGrossNoncurrent',
                    'us-gaap:EquitySecuritiesFvNiCurrentAndNoncurrent', 'loc_OtherInvestments', 'loc_RealEstateInvestmentsUnconsolidatedRealEstateAndOtherJointVentures', 'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesAfterFiveThroughTenYearsNetCarryingAmount',
                    'loc_HeldToMaturitySecuritiesNoncurrent', 'us-gaap:DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossCurrent', 'loc_CashCollateralForBorrowedSecurities', 'us-gaap:Investments',
                    'us-gaap:AccountsReceivableGrossNoncurrent', 'loc_LandAvailableForDevelopment', 'us-gaap:LongTermInvestmentsAndReceivablesNet', 'loc_MortgageLoansOnRealEstateCommercialAndConsumerNet', 'us-gaap:AccountsReceivableNetNoncurrent',
                    'loc_EquityMethodInvestments', 'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesAfterTenYearsNetCarryingAmount', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesWithoutSingleMaturityDateFairValue', 'loc_SecuritiesPurchasedUnderAgreementsToResell',
                    'us-gaap:HeldToMaturitySecuritiesNoncurrent', 'loc_OtherInvestmentsAndSecuritiesAtCost', 'us-gaap:InvestmentInPhysicalCommodities', 'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesAfterOneThroughFiveYearsNetCarryingAmount', 'loc_DebtSecurities',
                    'loc_RealEstateInvestmentNonincomeProducing', 'loc_OtherShortTermInvestments', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesAfterTenYearsFairValue', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesAfterOneThroughFiveYearsFairValue',
                    'us-gaap:OtherInvestmentsAndSecuritiesAtCost', 'loc_Land', 'us-gaap:DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLoss', 'loc_HeldToMaturitySecuritiesCurrent', 'us-gaap:CryptoAssetFairValueCurrent',
                    'loc_RealEstateAcquiredThroughForeclosure', 'loc_NotesReceivableGross', 'loc_RealEstateInvestmentsOther', 'us-gaap:DebtSecuritiesHeldToMaturityAllowanceForCreditLossNoncurrent', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesSingleMaturityDate',
                    'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesNoncurrent', 'loc_RentalProperties', 'loc_InterestsContinuedToBeHeldByTransferorFairValue', 'us-gaap:EquitySecuritiesFVNINoncurrent', 'loc_EquitySecuritiesFvNiCurrentAndNoncurrent',
                    'us-gaap:DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossNoncurrent', 'loc_OtherLongTermInvestments', 'loc_AdvancesToAffiliate', 'us-gaap:AvailableForSaleSecuritiesDebtSecurities', 'us-gaap:OtherShortTermInvestments',
                    'us-gaap:HeldToMaturitySecuritiesCurrent', 'us-gaap:MarketableSecuritiesCurrent', 'loc_DerivativeAssets', 'loc_TradingSecuritiesDebt', 'us-gaap:AuctionRateSecuritiesNoncurrent', 'us-gaap:EquityMethodInvestments',
                    'loc_DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLoss', 'us-gaap:EquitySecuritiesFvNi', 'us-gaap:AvailableForSaleSecuritiesDebtMaturitiesAfterFiveThroughTenYearsFairValue', 'loc_MarketableSecuritiesNoncurrent',
                    'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesWithoutSingleMaturityDateNetCarryingAmount', 'loc_DebtSecuritiesHeldToMaturityAllowanceForCreditLoss', 'us-gaap:RestrictedCashAndInvestmentsCurrent',
                    'us-gaap:LongTermAccountsNotesAndLoansReceivableNetNoncurrent', 'us-gaap:AllowanceForNotesAndLoansReceivableNoncurrent', 'loc_LandImprovements', 'loc_RealEstateInvestments', 'loc_AvailableForSaleSecuritiesDebtSecurities',
                    'loc_RealEstateInvestmentsJointVentures', 'loc_RealEstateInvestmentPropertyAccumulatedDepreciation', 'us-gaap:AllowanceForDoubtfulAccountsReceivableNoncurrent', 'loc_LandAndLandImprovements', 'us-gaap:OtherInvestments',
                    'us-gaap:HeldToMaturitySecuritiesDebtMaturitiesWithinOneYearNetCarryingAmount', 'loc_InvestmentBuildingAndBuildingImprovements', 'us-gaap:InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures', 'loc_LoansInsurancePolicy'},

    # append to long  term debt us-gaap:LongTermDebt
    # append to payables us-gaap:AccountsPayableCurrentAndNoncurrent us-gaap:AccountsPayableAndAccruedLiabilitiesCurrentAndNoncurrent
    'assets:': {'us-gaap:Assets'},
    'current_assets': {'us-gaap:AssetsCurrent'},
    'cash_and_short_term_investments': {'us-gaap:CashCashEquivalentsAndShortTermInvestments'},
    'cash_and_cash_equivalents': {'us-gaap:FederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResell', 'us-gaap:DueFromBanks', 'us-gaap:SecuritiesPurchasedUnderAgreementsToResell', 'us-gaap:RestrictedCashCurrent',
                                  'us-gaap:FederalFundsSoldAndSecuritiesPurchasedUnderAgreementsToResellPledgedAsCollateral', 'us-gaap:AssetBackedSecuritiesAtCarryingValue', 'us-gaap:CashEquivalentsAtCarryingValue',
                                  'us-gaap:FederalFundsSold', 'us-gaap:USGovernmentAgenciesSecuritiesAtCarryingValue', 'us-gaap:CertificatesOfDepositAtCarryingValue', 'us-gaap:CashUninsuredAmount',
                                  'us-gaap:RestrictedCashAndCashEquivalentsAtCarryingValue', 'us-gaap:CashCashEquivalentsAndFederalFundsSold', 'us-gaap:CommercialPaperAtCarryingValue',
                                  'us-gaap:MoneyMarketFundsAtCarryingValue', 'us-gaap:RestrictedCashEquivalentsCurrent', 'us-gaap:FederalFundsSoldAndSecuritiesBorrowedOrPurchasedUnderAgreementsToResellFairValueDisclosure',
                                  'us-gaap:CashAndCashEquivalentsAtCarryingValue', 'us-gaap:Cash', 'us-gaap:CashFDICInsuredAmount', 'us-gaap:MunicipalDebtSecuritiesAtCarryingValue', 'us-gaap:TimeDepositsAtCarryingValue',
                                  'us-gaap:InterestBearingDepositsInBanks', 'us-gaap:OtherCashEquivalentsAtCarryingValue', 'us-gaap:CreditAndDebitCardReceivablesAtCarryingValue', 'us-gaap:CashAndDueFromBanks',
                                  'us-gaap:USGovernmentSecuritiesAtCarryingValue'},
    'short_term_investments': {'us-gaap:ShortTermInvestments', 'us-gaap:EquitySecuritiesFvNi', 'us-gaap:MarketableSecuritiesCurrent', 'us-gaap:OtherShortTermInvestments',
                               'us-gaap:RestrictedInvestmentsCurrent', 'us-gaap:OtherRestrictedAssetsCurrent', 'us-gaap:RestrictedCashAndInvestmentsCurrent',
                               'us-gaap:HeldToMaturitySecuritiesCurrent', 'us-gaap:DebtSecuritiesHeldToMaturityAllowanceForCreditLossCurrent', 'us-gaap:DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossCurrent',
                               'us-gaap:TradingSecuritiesDebt', 'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesCurrent', 'us-gaap:DebtSecuritiesCurrent', 'us-gaap:CryptoAssetFairValueCurrent'},
    'net_receivables': {'us-gaap:PremiumsReceivableAllowanceForDoubtfulAccounts', 'us-gaap:AccountsReceivableBilledForLongTermContractsOrPrograms', 'us-gaap:NontradeReceivablesCurrent', 'us-gaap:NotesAndLoansReceivableNetCurrent',
                        'us-gaap:ReceivablesLongTermContractsOrPrograms', 'us-gaap:DepositDerivativeContract', 'us-gaap:PremiumsAndOtherReceivablesNet', 'us-gaap:LoansReceivableHeldForSaleAmount', 'us-gaap:InterestReceivable',
                        'us-gaap:AccountsReceivableNetCurrent', 'us-gaap:OtherReceivablesFromBrokerDealersAndClearingOrganizations', 'us-gaap:NotesReceivableGross', 'us-gaap:FinancingReceivableAllowanceForCreditLosses',
                        'us-gaap:IncomeTaxReceivable', 'us-gaap:AccountsNotesAndLoansReceivableNetCurrent', 'us-gaap:AccountsReceivableFromSecuritization', 'us-gaap:UnbilledContractsReceivable', 'us-gaap:AllowanceForDoubtfulAccountsReceivable',
                        'us-gaap:DepositSecuritySoldShort', 'us-gaap:NotesAndLoansReceivableGrossCurrent', 'us-gaap:NotesReceivableNet', 'us-gaap:UnbilledReceivablesCurrent', 'us-gaap:ReceivablesFromCustomers',
                        'us-gaap:AccruedInvestmentIncomeReceivable', 'us-gaap:GoodFaithAndMarginDepositsWithBrokerDealers', 'us-gaap:DepositsPaidForSecuritiesBorrowedAtCarryingValue', 'us-gaap:CommissionsAndFloorBrokerageReceivables',
                        'us-gaap:AllowanceForDoubtfulAccountsReceivableCurrent', 'us-gaap:PremiumsReceivableGross', 'us-gaap:ReceivablesFromBrokersDealersAndClearingOrganizations', 'us-gaap:AccruedFeesAndOtherRevenueReceivable',
                        'us-gaap:VariationMarginReceivableDerivative', 'us-gaap:AccountsReceivableGross', 'us-gaap:DueFromCorrespondentBrokers', 'us-gaap:PremiumsReceivableAtCarryingValue', 'us-gaap:SecuritiesFailedToDeliver',
                        'us-gaap:ReceivableInvestmentSale', 'us-gaap:AccountsReceivableNet', 'us-gaap:AccountsAndOtherReceivablesNetCurrent', 'us-gaap:ReceivablesNetCurrent', 'us-gaap:AccountsReceivableGrossCurrent',
                        'us-gaap:AllowanceForNotesAndLoansReceivableCurrent', 'us-gaap:ReceivablesFromClearingOrganizations'},
    'inventory': {'us-gaap:OtherInventory', 'us-gaap:RetailRelatedInventory', 'us-gaap:RetailRelatedInventoryMerchandise', 'us-gaap:AirlineRelatedInventoryNet', 'us-gaap:InventoryFinishedGoodsAndWorkInProcessNetOfReserves',
                  'us-gaap:AgriculturalRelatedInventory', 'us-gaap:EnergyRelatedInventoryPetroleum', 'us-gaap:OtherInventorySupplies', 'us-gaap:CrudeOilAndNaturalGasLiquids', 'us-gaap:EnergyRelatedInventoryGasStoredUnderground',
                  'us-gaap:AgriculturalRelatedInventoryGrowingCrops', 'us-gaap:EnergyRelatedInventoryPropaneGas', 'us-gaap:InventoryAdjustments', 'us-gaap:OtherInventoryNetOfReserves', 'us-gaap:OtherInventoryInTransit', 'us-gaap:InventoryFinishedGoods',
                  'us-gaap:InventoryCrudeOilProductsAndMerchandise', 'us-gaap:InventoryRawMaterialsAndSupplies', 'us-gaap:OtherInventoryCapitalizedCosts', 'us-gaap:EnergyRelatedInventoryChemicals', 'us-gaap:OtherInventoryWarehouse',
                  'us-gaap:EnergyRelatedInventory', 'us-gaap:InventoryRawMaterialsAndSuppliesNetOfReserves', 'us-gaap:RetailRelatedInventoryPackagingAndOtherSupplies', 'us-gaap:EnergyRelatedInventoryOtherFossilFuel', 'us-gaap:OtherInventoryInventoryAtOffSitePremises',
                  'us-gaap:AirlineRelatedInventory', 'us-gaap:OtherInventoryPurchasedGoods', 'us-gaap:OtherInventoryDemo', 'us-gaap:InventoryRawMaterialsNetOfReserves', 'us-gaap:OtherInventoryScrap', 'us-gaap:InventoryGross',
                  'us-gaap:InventoryFinishedGoodsNetOfReserves', 'us-gaap:AgriculturalRelatedInventoryPlantMaterial', 'us-gaap:InventoryWorkInProcess', 'us-gaap:OtherInventoryMaterialsSuppliesAndMerchandiseUnderConsignment',
                  'us-gaap:OtherInventoriesSpareParts', 'us-gaap:AirlineRelatedInventoryValuationReserves', 'us-gaap:EnergyRelatedInventoryNaturalGasInStorage', 'us-gaap:AirlineRelatedInventoryAircraftParts', 'us-gaap:EnergyRelatedInventoryNaturalGasLiquids',
                  'us-gaap:InventoryPartsAndComponentsNetOfReserves', 'us-gaap:InventoryOreStockpilesOnLeachPads', 'us-gaap:PublicUtilitiesInventory', 'us-gaap:InventoryValuationReserves', 'us-gaap:InventoryRawMaterials', 'us-gaap:InventorySuppliesNetOfReserves',
                  'us-gaap:InventoryFinishedGoodsAndWorkInProcess', 'us-gaap:AirlineRelatedInventoryAircraftFuel', 'us-gaap:EnergyRelatedInventoryCoal', 'us-gaap:InventoryWorkInProcessNetOfReserves', 'us-gaap:InventoryForLongTermContractsOrPrograms',
                  'us-gaap:AgriculturalRelatedInventoryFeedAndSupplies', 'us-gaap:InventoryLIFOReserve', 'us-gaap:InventoryNet'},
    'other_current_assets': None, # must be calculated
    'non_current_assets': None,
    'property_plant_equipment_net': {'us-gaap:TimberAndTimberlands', 'us-gaap:BuildingsAndImprovementsGross', 'us-gaap:CapitalizedComputerSoftwareGross', 'us-gaap:LandImprovements', 'us-gaap:FixturesAndEquipmentGross', 'us-gaap:PropertyPlantAndEquipmentGross', 'us-gaap:ConstructionInProgressGross', 'us-gaap:PropertyPlantAndEquipmentOther',
                                     'us-gaap:PropertyPlantAndEquipmentExcludingLessorAssetUnderOperatingLeaseBeforeAccumulatedDepreciation', 'us-gaap:LandAndLandImprovements', 'us-gaap:PropertyPlantAndEquipmentNet', 'us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment',
                                     'us-gaap:PropertySubjectToOrAvailableForOperatingLeaseGross', 'us-gaap:LeaseholdImprovementsGross', 'us-gaap:FurnitureAndFixturesGross', 'us-gaap:Land', 'us-gaap:MachineryAndEquipmentGross',
                                     'us-gaap:PropertyPlantAndEquipmentAndFinanceLeaseRightOfUseAssetAfterAccumulatedDepreciationAndAmortization'},
    'operating_lease': {'us-gaap:OperatingLeaseRightOfUseAsset'},
    'goodwill': {'us-gaap:Goodwill', 'us-gaap:GoodwillTransfers', 'us-gaap:GoodwillForeignCurrencyTranslationGainLoss'
                 'us-gaap:GoodwillWrittenOffRelatedToSaleOfBusinessUnit', 'us-gaap:GoodwillOtherIncreaseDecrease', 'us-gaap:GoodwillSubsequentRecognitionOfDeferredTaxAsset',
                 'us-gaap:GoodwillImpairmentLoss', 'us-gaap:GoodwillAcquiredDuringPeriod', 'us-gaap:GoodwillPurchaseAccountingAdjustments', 'us-gaap:us-gaap:GoodwillTranslationAndPurchaseAccountingAdjustments'},
    'intangible_assets': {'us-gaap:FiniteLivedIntangibleAssetsGross', 'us-gaap:FiniteLivedIntangibleAssetsAccumulatedAmortization', 'us-gaap:IntangibleAssetsNetExcludingGoodwill', 'us-gaap:IndefiniteLivedIntangibleAssetsExcludingGoodwill', 'us-gaap:FiniteLivedIntangibleAssetsNet'},
    'long_term_investments': {'us-gaap:InvestmentInPhysicalCommodities', 'us-gaap:OtherLongTermInvestments', 'us-gaap:AuctionRateSecuritiesNoncurrent', 'us-gaap:AllowanceForNotesAndLoansReceivableNoncurrent', 'us-gaap:InvestmentsInAffiliatesSubsidiariesAssociatesAndJointVentures', 'us-gaap:EquityMethodInvestments',
                              'us-gaap:MarketableSecuritiesNoncurrent', 'us-gaap:EquitySecuritiesFVNINoncurrent', 'us-gaap:LongTermInvestmentsAndReceivablesNet', 'us-gaap:LongTermAccountsNotesAndLoansReceivableNetNoncurrent', 'us-gaap:AccountsReceivableNetNoncurrent',
                              'us-gaap:DebtSecuritiesHeldToMaturityAllowanceForCreditLossNoncurrent', 'us-gaap:AllowanceForDoubtfulAccountsReceivableNoncurrent', 'us-gaap:HeldToMaturitySecuritiesNoncurrent', 'us-gaap:AdvancesToAffiliate', 'us-gaap:DebtSecuritiesNoncurrent',
                              'us-gaap:NotesAndLoansReceivableGrossNoncurrent', 'us-gaap:AccountsReceivableGrossNoncurrent', 'us-gaap:NotesAndLoansReceivableNetNoncurrent', 'us-gaap:AvailableForSaleSecuritiesDebtSecuritiesNoncurrent', 'us-gaap:LongTermInvestments', 'us-gaap:DebtSecuritiesHeldToMaturityAmortizedCostAfterAllowanceForCreditLossNoncurrent',
                              'us-gaap:CryptoAssetFairValueNoncurrent'},
    'non_current_deferred_assets': {'us-gaap:DeferredIncomeTaxAssetsNet', 'us-gaap:DeferredTaxAssetsDeferredIncome'},
    'other_non_current_assets': None, # Calculated
    'liabilities_and_equity': {'us-gaap:LiabilitiesAndStockholdersEquity'}, # delete during balance_sheet validation
    'liabilities': {'us-gaap:Liabilities'},
    'current_liabilities': {'us-gaap:LiabilitiesCurrent'},
    'payables_and_expenses': {'us-gaap:AccountsPayableAndAccruedLiabilitiesCurrent'},
    'account_payables': {'us-gaap:AccountsPayableCurrent', 'us-gaap:AccountsPayableOtherCurrent', 'us-gaap:AccountsPayableUnderwritersPromotersAndEmployeesOtherThanSalariesAndWagesCurrent',
                         'us-gaap:GasImbalancePayableCurrent', 'us-gaap:EnergyMarketingAccountsPayable', 'us-gaap:GasPurchasePayableCurrent','us-gaap:OilAndGasSalesPayableCurrent',
                         'us-gaap:ConstructionPayableCurrent', 'us-gaap:AccountsPayableInterestBearingCurrent', 'us-gaap:AccountsPayableTradeCurrent', 'us-gaap:InterestPayableCurrent',
                         'us-gaap:DividendsPayableCurrent', 'us-gaap:SalesAndExciseTaxPayableCurrent'},
    'accrued_liabilities_current':{'us-gaap:AccruedBonusesCurrent', 'us-gaap:AccruedRentCurrent', 'us-gaap:PensionAndOtherPostretirementAndPostemploymentBenefitPlansLiabilitiesCurrent', 'us-gaap:EmployeeRelatedLiabilitiesCurrent', 'us-gaap:AccruedPayrollTaxesCurrent', 'us-gaap:StandardProductWarrantyAccrualCurrent', 'us-gaap:AccruedVacationCurrent',
                                   'us-gaap:AccruedLiabilitiesCurrent', 'us-gaap:WorkersCompensationLiabilityCurrent', 'us-gaap:TaxCutsAndJobsActOf2017TransitionTaxForAccumulatedForeignEarningsLiabilityCurrent', 'us-gaap:AccruedInsuranceCurrent', 'us-gaap:AccruedUtilitiesCurrent', 'us-gaap:DefinedBenefitPensionPlanLiabilitiesCurrent',
                                   'us-gaap:AccruedSalesCommissionCurrent', 'us-gaap:AccruedSalariesCurrent', 'us-gaap:ExtendedProductWarrantyAccrualCurrent', 'us-gaap:AccruedRoyaltiesCurrent', 'us-gaap:AccruedIncomeTaxesCurrent', 'us-gaap:AccruedEmployeeBenefitsCurrent', 'us-gaap:AccruedProfessionalFeesCurrent', 'us-gaap:SettlementLiabilitiesCurrent',
                                   'us-gaap:AccrualForTaxesOtherThanIncomeTaxesCurrent', 'us-gaap:AccruedExchangeFeeRebateCurrent', 'us-gaap:OtherAccruedLiabilitiesCurrent', 'us-gaap:PensionAndOtherPostretirementDefinedBenefitPlansCurrentLiabilities', 'us-gaap:OtherEmployeeRelatedLiabilitiesCurrent', 'us-gaap:AccruedMarketingCostsCurrent',
                                   'us-gaap:ProductWarrantyAccrualClassifiedCurrent', 'us-gaap:AccruedAdvertisingCurrent'},
    'short_term_debt': {'us-gaap:SubordinatedDebtCurrent', 'us-gaap:OperatingLeaseLiabilityCurrent', 'us-gaap:ShortTermBorrowings', 'us-gaap:LoansPayableToBankCurrent', 'us-gaap:SeniorNotesCurrent', 'us-gaap:ShortTermDebtRecourseStatusExtensibleEnumeration', 'us-gaap:ShortTermBankLoansAndNotesPayable', 'us-gaap:LongTermDebtCurrent', 'us-gaap:OtherNotesPayableCurrent',
                        'us-gaap:JuniorSubordinatedNotesCurrent', 'us-gaap:FinanceLeaseLiabilityCurrent', 'us-gaap:LinesOfCreditCurrent', 'us-gaap:LoansPayableCurrent', 'us-gaap:MediumtermNotesCurrent', 'us-gaap:ConvertibleNotesPayableCurrent', 'us-gaap:JuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustCurrent',
                        'us-gaap:SecuredDebtCurrent', 'us-gaap:LongTermConstructionLoanCurrent', 'us-gaap:LongtermTransitionBondCurrent', 'us-gaap:OtherLoansPayableCurrent', 'us-gaap:NotesPayableCurrentRelatedPartyTypeExtensibleEnumeration', 'us-gaap:ConstructionLoan', 'us-gaap:NotesPayableCurrent', 'us-gaap:BankOverdrafts',
                        'us-gaap:NotesPayableCurrentRelatedPartyCounterpartyNameExtensibleEnumeration', 'us-gaap:NotesAndLoansPayableCurrent', 'us-gaap:LongTermDebtAndCapitalLeaseObligationsCurrent', 'us-gaap:FederalHomeLoanBankAdvancesCurrent', 'us-gaap:LongTermDebtCurrentRecourseStatusExtensibleEnumeration', 'us-gaap:BridgeLoan',
                        'us-gaap:LongtermPollutionControlBondCurrent', 'us-gaap:ShortTermNonBankLoansAndNotesPayable', 'us-gaap:OtherShortTermBorrowings', 'us-gaap:LongTermCommercialPaperCurrent', 'us-gaap:OtherLongTermDebtCurrent', 'us-gaap:DebtCurrent', 'us-gaap:NotesPayableToBankCurrent', 'us-gaap:UnsecuredDebtCurrent',
                        'us-gaap:CommercialPaper', 'us-gaap:ConvertibleDebtCurrent', 'us-gaap:ConvertibleSubordinatedDebtCurrent', 'us-gaap:SpecialAssessmentBondCurrent'},
    'other_current_liabilities': None,
    'non_current_liabilities': {'us-gaap:LiabilitiesNoncurrent'},
    'long_term_debt': {'us-gaap:LongTermDebtNoncurrent', 'us-gaap:OperatingLeaseLiabilityNoncurrent', 'us-gaap:LongTermLineOfCredit', 'us-gaap:SeniorLongTermNotes', 'us-gaap:LongTermLoansFromBank', 'us-gaap:SecuredLongTermDebt', 'us-gaap:UnsecuredLongTermDebt',
                       'us-gaap:JuniorSubordinatedDebentureOwedToUnconsolidatedSubsidiaryTrustNoncurrent', 'us-gaap:LongTermPollutionControlBond', 'us-gaap:LongTermNotesPayable', 'us-gaap:CommercialPaperNoncurrent', 'us-gaap:SpecialAssessmentBondNoncurrent',
                       'us-gaap:LongtermFederalHomeLoanBankAdvancesNoncurrent', 'us-gaap:LongTermLoansPayable', 'us-gaap:ConvertibleSubordinatedDebtNoncurrent', 'us-gaap:JuniorSubordinatedLongTermNotes', 'us-gaap:LongTermDebtAndCapitalLeaseObligations', 'us-gaap:NotesPayableToBankNoncurrent',
                       'us-gaap:ConvertibleLongTermNotesPayable', 'us-gaap:OtherLongTermNotesPayable', 'us-gaap:SubordinatedLongTermDebt', 'us-gaap:ConvertibleDebtNoncurrent', 'us-gaap:LongTermTransitionBond', 'us-gaap:FinanceLeaseLiabilityNoncurrent', 'us-gaap:ConstructionLoanNoncurrent',
                       'us-gaap:OtherLongTermDebtNoncurrent', 'us-gaap:OtherLoansPayableLongTerm', 'us-gaap:LongTermNotesAndLoans', 'us-gaap:MediumtermNotesNoncurrent'},
    'other_non_current_liabilities': None, # Calculated
    'equity': {'us-gaap:StockholdersEquityIncludingPortionAttributableToNoncontrollingInterest'},
    'minority_interest': {'us-gaap:MinorityInterest'},
    'shareholders_equity': {'us-gaap:StockholdersEquity'},
    'capital_stock': {'us-gaap:CommonStockValue', 'us-gaap:CommonStockValueOutstanding', 'us-gaap:PreferredStockValue', 'us-gaap:PreferredStockValueOutstanding', 'CommonStocksIncludingAdditionalPaidInCapital'},
    'share_premium': {'us-gaap:AdditionalPaidInCapital', 'us-gaap:AdditionalPaidInCapitalCommonStock', 'us-gaap:AdditionalPaidInCapitalPreferredStock', 'us-gaap:OtherAdditionalCapital'},
    'retained_earnings': {'us-gaap:RetainedEarningsAccumulatedDeficit', 'us-gaap:RetainedEarningsAppropriated', 'us-gaap:RetainedEarningsUnappropriated'},
    'treasury_shares': {'us-gaap:TreasuryStockValue', 'us-gaap:TreasuryStockCommonValue', 'us-gaap:TreasuryStockPreferredValue'},
    'accumulated_other_comprehensive_income_loss': {'us-gaap:AociLiabilityForFuturePolicyBenefitAfterTax', 'us-gaap:AccumulatedOtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax',
                                                    'us-gaap:AccumulatedOtherComprehensiveIncomeLossDefinedBenefitPensionAndOtherPostretirementPlansNetOfTax',
                                                    'us-gaap:AociLossCashFlowHedgeCumulativeGainLossAfterTax', 'us-gaap:AccumulatedOtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentNetOfTax',
                                                    'us-gaap:AociDerivativeQualifyingAsHedgeExcludedComponentAfterTax', 'us-gaap:AccumulatedOtherComprehensiveIncomeLossFinancialLiabilityFairValueOptionAfterTax',
                                                    'us-gaap:AociMarketRiskBenefitInstrumentSpecificCreditRiskAfterTax', 'us-gaap:AccumulatedOtherComprehensiveIncomeLossNetOfTax'}

}

income_statement_gaap = {
    'interest_income_b': {'us-gaap:InterestAndDividendIncomeOperating', 'us-gaap:InterestIncomeOperating'},
    'interest_expense_b': {'us-gaap:InterestExpenseOperating', 'us-gaap:InterestExpense'},
    'net_interest_b': {'us-gaap:InterestIncomeExpenseNet'},
    'non_interest_income_b': {'us-gaap:NoninterestIncome'},
    'non_interest_expense_b': {'us-gaap:NoninterestExpense'}, # actually operating expenses
    'provisions_credit_losses': {'us-gaap:ProvisionForLoanLossesExpensed', 'us-gaap:ProvisionForLoanLeaseAndOtherLosses'},
    'ner_premiums': {'us-gaap:PremiumsEarnedNet'},
    'revenue': {'us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax', 'us-gaap:Revenues', 'us-gaap:RevenuesNetOfInterestExpense', 'us-gaap:PremiumsWrittenGross', 'us-gaap:PremiumsWrittenNet', 'us-gaap:RevenueFromContractWithCustomerIncludingAssessedTax'},
    'cost_of_revenue': {'us-gaap:CostOfRevenue', 'us-gaap:CostOfGoodsAndServicesSold', 'us-gaap:MerchantMarineOperatingDifferentialSubsidy', 'us-gaap:ReinsuranceEffectOnClaimsAndBenefitsIncurredAmountCeded',
                        'us-gaap:InterestCreditedToPolicyholdersAccountBalances', 'us-gaap:FuelCosts', 'us-gaap:ExciseAndSalesTaxes', 'us-gaap:CostOfGoodsAndServiceExcludingDepreciationDepletionAndAmortization',
                        'us-gaap:CostDirectMaterial', 'us-gaap:DirectOperatingCommunicationsCosts', 'us-gaap:CostDepreciationAmortizationAndDepletion', 'us-gaap:ManufacturingCosts', 'us-gaap:CostOfPropertyRepairsAndMaintenance',
                        'us-gaap:CostOfGoodsAndServicesSoldAmortization', 'us-gaap:OperatingInsuranceAndClaimsCostsProduction', 'us-gaap:CostOfTrustAssetsSoldToPayExpenses', 'us-gaap:CostDepletion', 'us-gaap:CostOfGoodsSoldDirectFinancingLease',
                        'us-gaap:AmortizationOfValueOfBusinessAcquiredVOBA', 'us-gaap:LossOnContracts', 'us-gaap:ProvisionForOtherCreditLosses', 'us-gaap:PresentValueOfFutureInsuranceProfitsAmortizationExpense1',
                        'us-gaap:AmortizationOfMortgageServicingRightsMSRs', 'us-gaap:DirectOperatingMaintenanceSuppliesCosts', 'us-gaap:CostMaintenance', 'us-gaap:ReinsuranceCostsAndRecoveriesNet',
                        'us-gaap:DeferredSalesInducementsAmortizationExpense', 'us-gaap:DirectOperatingCosts', 'us-gaap:InventoryWriteDown', 'us-gaap:AffiliateCosts', 'us-gaap:AircraftRentalAndLandingFees',
                        'us-gaap:RecoveryOfDirectCosts', 'us-gaap:OtherCostOfOperatingRevenue', 'us-gaap:CostOfGoodsSoldSalesTypeLease', 'us-gaap:CostOfGoodsAndServicesSoldDepreciation', 'us-gaap:LandingFeesAndOtherRentals',
                        'us-gaap:ReinsuranceEffectOnClaimsAndBenefitsIncurredAmountAssumed', 'us-gaap:CostOfGoodsAndServicesSoldDepreciationAndAmortization', 'us-gaap:LiabilityForFuturePolicyBenefitsPeriodExpense',
                        'us-gaap:CostOfOtherPropertyOperatingExpense', 'us-gaap:AircraftRental', 'us-gaap:PolicyholderDividends', 'us-gaap:PolicyholderBenefitsAndClaimsIncurredGross',
                        'us-gaap:ProvisionForLoanLeaseAndOtherLosses', 'us-gaap:InventoryFirmPurchaseCommitmentLoss', 'us-gaap:WaterProductionCosts', 'us-gaap:ProvisionForOtherLosses',
                        'us-gaap:DirectCostsOfLeasedAndRentedPropertyOrEquipment', 'us-gaap:CostOfGoodsAndServicesSoldOverhead', 'us-gaap:DirectCommunicationsAndUtilitiesCosts', 'us-gaap:PolicyholderBenefitsAndClaimsIncurredNet',
                        'us-gaap:FinancingInterestExpense', 'us-gaap:ProvisionForLoanLossesExpensed', 'us-gaap:DeferredPolicyAcquisitionCostAmortizationExpense', 'us-gaap:CostDirectLabor', 'us-gaap:DirectTaxesAndLicensesCosts',
                        'us-gaap:CostOfPurchasedWater', 'us-gaap:NetInvestmentInLeaseCreditLossExpenseReversal', 'us-gaap:ProductionRelatedImpairmentsOrCharges'},
    'gross_profit': {'us-gaap:GrossProfit'},
    'operating_expenses': {'us-gaap:OperatingExpenses', 'us-gaap:OperatingCostsAndExpenses', 'us-gaap:EnvironmentalCostsRecognizedRecoveryCreditedToExpense', 'us-gaap:ImpairmentExcludingLessorAssetUnderOperatingLease',
                           'us-gaap:GainLossOnSaleOfProvedProperty', 'us-gaap:ImpairmentOfOngoingProject', 'us-gaap:CustodyFees', 'us-gaap:RoyaltyExpense', 'us-gaap:GainLossOnSaleOfTimberProperty', 'us-gaap:AmortizationOfNuclearFuelLease',
                           'us-gaap:ImpairmentOfLongLivedAssetsHeldForUse', 'us-gaap:ImpairmentLossesRelatedToRealEstatePartnerships', 'us-gaap:SeveranceCosts1', 'us-gaap:EquityMethodInvestmentOtherThanTemporaryImpairment', 'us-gaap:ImpairmentOfRealEstate',
                           'us-gaap:BusinessCombinationIntegrationRelatedCosts', 'us-gaap:AmortizationOfRateDeferral', 'us-gaap:AmortizationOfRegulatoryAsset', 'us-gaap:InsuranceTax', 'us-gaap:InsuranceRecoveries', 'us-gaap:GainLossOnSaleOfUnprovedProperty',
                           'us-gaap:RestructuringSettlementAndImpairmentProvisions', 'us-gaap:OfficersCompensation', 'us-gaap:ManagementFeeExpense', 'us-gaap:DirectFinancingLeaseImpairmentLoss', 'us-gaap:TangibleAssetImpairmentCharges',
                           'us-gaap:MalpracticeLossContingencyClaimsIncurredNet', 'us-gaap:RestructuringCharges', 'us-gaap:AssetImpairmentCharges', 'us-gaap:FloorBrokerage', 'us-gaap:OtherGeneralAndAdministrativeExpense',
                           'us-gaap:EnvironmentalRemediationExpense', 'us-gaap:SponsorFees', 'us-gaap:SalesTypeLeaseSellingProfitLoss', 'us-gaap:AllocatedShareBasedCompensationExpense', 'us-gaap:SalesTypeLeaseImpairmentLoss',
                           'us-gaap:OtherRestructuringCosts', 'us-gaap:IncentiveFeeExpense', 'us-gaap:ProfessionalAndContractServicesExpense', 'us-gaap:GovernmentAssistanceOperatingExpense', 'us-gaap:ImpairmentOfOilAndGasProperties',
                           'us-gaap:ResearchAndDevelopmentAssetAcquiredOtherThanThroughBusinessCombinationWrittenOff', 'us-gaap:ResearchAndDevelopmentExpenseSoftwareExcludingAcquiredInProcessCost', 'us-gaap:OtherSellingAndMarketingExpense',
                           'us-gaap:TravelAndEntertainmentExpense', 'us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost', 'us-gaap:GainLossOnSaleOfOilAndGasProperty', 'us-gaap:MalpracticeLossContingencyClaimsIncurredInPeriod',
                           'us-gaap:CommunicationsInformationTechnologyAndOccupancy', 'us-gaap:LegalFees', 'us-gaap:LitigationSettlementLoss', 'us-gaap:IncentiveFeeExpenseCapitalGainBased', 'us-gaap:DepletionOfOilAndGasProperties',
                           'us-gaap:InformationTechnologyAndDataProcessing', 'us-gaap:CommunicationsAndInformationTechnology', 'us-gaap:OccupancyNet', 'us-gaap:PostageExpense', 'us-gaap:ClearanceFees', 'us-gaap:PumpTaxes',
                           'us-gaap:OtherSellingGeneralAndAdministrativeExpense', 'us-gaap:SalariesAndWages', 'us-gaap:SuppliesAndPostageExpense', 'us-gaap:InventoryRecallExpense', 'us-gaap:DirectFinancingLeaseSellingLoss', 'us-gaap:ExplorationExpense',
                           'us-gaap:ImpairmentOfIntangibleAssetsFinitelived', 'us-gaap:DisposalGroupNotDiscontinuedOperationLossGainOnWriteDown', 'us-gaap:SaleAndLeasebackTransactionGainLossNet', 'us-gaap:MalpracticeLossContingencyInsuranceRecoveries',
                           'us-gaap:TrusteeFees', 'us-gaap:ImpairmentLessorAssetUnderOperatingLease', 'us-gaap:IncentiveFeeExpenseIncomeBased', 'us-gaap:GainLossOnTerminationOfLease', 'us-gaap:AdministrativeFeesExpense', 'us-gaap:OtherUnderwritingExpense',
                           'us-gaap:AmortizationOfDeferredPropertyTaxes', 'us-gaap:GainLossOnDispositionOfAssets', 'us-gaap:DefinedBenefitPlanRecognizedNetGainLossDueToSettlements1', 'us-gaap:GainOnBusinessInterruptionInsuranceRecovery',
                           'us-gaap:ProductWarrantyExpense', 'us-gaap:ManagementAndIncentiveFeesExpense', 'us-gaap:FinanceLeaseRightOfUseAssetAmortization', 'us-gaap:ImpairmentOfLeasehold', 'us-gaap:LoanPortfolioExpense',
                           'us-gaap:CarryingCostsPropertyAndExplorationRights', 'us-gaap:SellingExpense', 'us-gaap:OtherLaborRelatedExpenses', 'us-gaap:GeneralAndAdministrativeExpense', 'us-gaap:GainLossOnDispositionOfAssets1',
                           'us-gaap:LitigationSettlementInterest', 'us-gaap:BusinessCombinationAcquisitionRelatedCosts', 'us-gaap:DepreciationAndAmortization', 'us-gaap:AccretionExpense', 'us-gaap:RealEstateInsurance', 'us-gaap:ProvisionForDoubtfulAccounts',
                           'us-gaap:AffordableHousingProjectInvestmentWriteDownAmount', 'us-gaap:AccretionExpenseIncludingAssetRetirementObligations', 'us-gaap:OtherGeneralExpense', 'us-gaap:AmortizationAndDepreciationOfDecontaminatingAndDecommissioningAssets',
                           'us-gaap:BusinessDevelopment', 'us-gaap:AdvertisingExpense', 'us-gaap:AmortizationOfDeferredHedgeGains', 'us-gaap:OtherDepreciationAndAmortization', 'us-gaap:ProfessionalFees', 'us-gaap:TaxesExcludingIncomeAndExciseTaxes',
                           'us-gaap:ImpairmentOfIntangibleAssetsIndefinitelivedExcludingGoodwill', 'us-gaap:LitigationSettlementExpense', 'us-gaap:FranchisorCosts', 'us-gaap:SuppliesExpense', 'us-gaap:MalpracticeLossContingencyClaimsIncurredInPriorPeriods',
                           'us-gaap:UnsolicitedTenderOfferCosts', 'us-gaap:BusinessExitCosts1', 'us-gaap:LitigationSettlementGain', 'us-gaap:GainLossOnSaleOfOtherAssets', 'us-gaap:CostsOfFranchisorOwnedOutlets', 'us-gaap:RealEstateTaxExpense',
                           'us-gaap:GoodwillAndIntangibleAssetImpairment', 'us-gaap:SellingAndMarketingExpense', 'us-gaap:GeneralInsuranceExpense', 'us-gaap:AmortizationOfDeferredSalesCommissions', 'us-gaap:AmortizationOfPowerContractsEmissionCredits',
                           'us-gaap:DepreciationNonproduction', 'us-gaap:TaxesOther', 'us-gaap:OrderFlowFees', 'us-gaap:ImpairmentOfLongLivedAssetsToBeDisposedOf', 'us-gaap:AssetRetirementObligationAccretionExpense', 'us-gaap:SalariesWagesAndOfficersCompensation',
                           'us-gaap:GainLossOnSaleOfBusiness', 'us-gaap:ImpairmentOfIntangibleAssetsExcludingGoodwill', 'us-gaap:ExchangeFees', 'us-gaap:SellingGeneralAndAdministrativeExpense', 'us-gaap:InsuranceCommissions',
                           'us-gaap:GainLossOnSaleOfPropertyPlantEquipment', 'us-gaap:MarketingAndAdvertisingExpense', 'us-gaap:AmortizationOfAcquisitionCosts', 'us-gaap:OperatingLeaseExpense', 'us-gaap:OtherCostAndExpenseOperating',
                           'us-gaap:GainLossOnDispositionOfIntangibleAssets', 'us-gaap:RecapitalizationCosts', 'us-gaap:PreOpeningCosts', 'us-gaap:CostsOfFranchisedOutlets', 'us-gaap:FloorBrokerageExchangeAndClearanceFees',
                           'us-gaap:MalpracticeLossContingencyReturnOfPremiums', 'us-gaap:EnvironmentalRemediationExpenseAfterRecovery', 'us-gaap:AmortizationOfIntangibleAssets', 'us-gaap:AmortizationOfAdvanceRoyalty',
                           'us-gaap:GainLossRelatedToLitigationSettlement', 'us-gaap:DemutualizationCostAndExpense', 'us-gaap:Communication', 'us-gaap:ResearchAndDevelopmentExpense', 'us-gaap:GoodwillImpairmentLoss', 'us-gaap:ProductionTaxExpense',
                           'us-gaap:MarketingExpense', 'us-gaap:ExplorationAbandonmentAndImpairmentExpense', 'us-gaap:LossContingencyLossInPeriod', 'us-gaap:GainLossOnSaleOfProperty', 'us-gaap:AmortizationOfDeferredCharges', 'us-gaap:SalesCommissionsAndFees',
                           'us-gaap:FinanceLeaseImpairmentLoss', 'us-gaap:OtherAmortizationOfDeferredCharges', 'us-gaap:OperatingLeaseImpairmentLoss'},
    'selling_general_and_administrative_expense': {'us-gaap:SellingGeneralAndAdministrativeExpense', 'us-gaap:GeneralAndAdministrativeExpense', # todo rename column
                                                   'us-gaap:MarketingExpense', 'us-gaap:AdvertisingExpense', 'us-gaap:CostsOfFranchisorOwnedOutlets',
                                                   'us-gaap:CostsOfFranchisedOutlets', 'us-gaap:SellingExpense', 'us-gaap:SalesCommissionsAndFees', 'us-gaap:MarketingAndAdvertisingExpense', 'us-gaap:FranchisorCosts', 'us-gaap:ProductWarrantyExpense',
                                                   'us-gaap:OtherSellingAndMarketingExpense', 'us-gaap:SalariesAndWages', 'us-gaap:OfficersCompensation', 'us-gaap:Communication', 'us-gaap:InformationTechnologyAndDataProcessing',
                                                   'us-gaap:CommunicationsAndInformationTechnology', 'us-gaap:OccupancyNet', 'us-gaap:SuppliesExpense', 'us-gaap:PostageExpense', 'us-gaap:RealEstateTaxExpense', 'us-gaap:ProductionTaxExpense',
                                                   'us-gaap:PumpTaxes', 'us-gaap:TaxesOther', 'us-gaap:AllocatedShareBasedCompensationExpense', 'us-gaap:SalariesWagesAndOfficersCompensation', 'us-gaap:OtherLaborRelatedExpenses', 'us-gaap:ProfessionalFees',
                                                   'us-gaap:BusinessDevelopment', 'us-gaap:GeneralInsuranceExpense', 'us-gaap:RealEstateInsurance', 'us-gaap:CommunicationsInformationTechnologyAndOccupancy', 'us-gaap:OperatingLeaseExpense',
                                                   'us-gaap:TravelAndEntertainmentExpense', 'us-gaap:SuppliesAndPostageExpense', 'us-gaap:InsuranceTax', 'us-gaap:TaxesExcludingIncomeAndExciseTaxes', 'us-gaap:OtherGeneralAndAdministrativeExpense',
                                                   'us-gaap:LossContingencyLossInPeriod', 'us-gaap:SellingAndMarketingExpense', 'us-gaap:GeneralAndAdministrativeExpense', 'us-gaap:OtherSellingGeneralAndAdministrativeExpense'},
    'research_and_development_expenses': {'us-gaap:ResearchAndDevelopmentExpense', 'us-gaap:ResearchAndDevelopmentExpenseExcludingAcquiredInProcessCost',
                                          'us-gaap:ResearchAndDevelopmentExpenseSoftwareExcludingAcquiredInProcessCost', 'us-gaap:ResearchAndDevelopmentAssetAcquiredOtherThanThroughBusinessCombinationWrittenOff'},
    'other_operating_expenses': None, # Calculated
    'operating_income': {'us-gaap:OperatingIncomeLoss'},
    'other_income_net': None,
    'expenses': None, # calculated
    'ebt': {'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesExtraordinaryItemsNoncontrollingInterest', 'us-gaap:IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments'},
    'income_equity_method_investments': {'us-gaap:IncomeLossFromEquityMethodInvestments'},
    'interest_expense': {'us-gaap:InterestExpense', 'us-gaap:InterestAndDebtExpense', 'us-gaap:InterestExpenseNonoperating'},
    'interest_inc_exp': {'us-gaap:InterestIncomeExpenseNonoperatingNet'},
    'ebit': None, # Calculated
    'reconciled_deprecation': None, # todo you need to find this value from cf stmt and maybe it's better to name it 'dda'. This is from cf us-gaap:DepreciationDepletionAndAmortization, us-gaap:DepreciationAndAmortization
    'ebitda': None, # Calculated
    'income_tax': {'us-gaap:IncomeTaxExpenseBenefit'},
    'net_income_including_non_controlling_interests': {'us-gaap:ProfitLoss'}, # todo new column, also this tag 'us-gaap:IncomeLossFromContinuingOperationsIncludingPortionAttributableToNoncontrollingInterest', but it must be only one of these tags for this position or in other words it cannot be sum.
    'net_income_non_controlling_interests': {'us-gaap:NetIncomeLossAttributableToNoncontrollingInterest'}, # todo new column
    'net_income': {'us-gaap:NetIncomeLoss', 'us-gaap:NetIncomeLossAvailableToCommonStockholdersBasic'},
    'eps': {'us-gaap:EarningsPerShareBasic'}, # todo rename column name 'eps_basic'
    'diluted_eps': {'us-gaap:EarningsPerShareDiluted'},
    'avg_shares_basic': {'us-gaap:WeightedAverageNumberOfSharesOutstandingBasic'}, # todo rename column name maybe
    'avg_shares_diluted': {'us-gaap:WeightedAverageNumberOfDilutedSharesOutstanding'}, # todo new column name
}


cash_flow_gaap = {
    # Operating cash flow
    'operating_cash_flow': {'us-gaap:NetCashProvidedByUsedInOperatingActivities', 'us-gaap:NetCashProvidedByUsedInOperatingActivitiesContinuingOperations', 'us-gaap:CashProvidedByUsedInOperatingActivitiesDiscontinuedOperations'}, # 1 = 2 + 3
    'operating_net_income': {'us-gaap:ProfitLoss', 'us-gaap:IncomeLossIncludingPortionAttributableToNoncontrollingInterest', 'us-gaap:NetIncomeLoss'},
    'operating_da': {'us-gaap:DepreciationAndAmortization', 'us-gaap:OperatingLeaseRightOfUseAssetAmortizationExpense', 'us-gaap:DepreciationDepletionAndAmortization', 'us-gaap:OtherDepreciationAndAmortization', 'us-gaap:CostOfGoodsAndServicesSoldDepreciation', # todo rename to dda
                     'us-gaap:CostOfGoodsAndServicesSoldDepreciation', 'us-gaap:DepreciationNonproduction', 'us-gaap:Depreciation', 'us-gaap:Depletion', 'us-gaap:CostDepletion', 'us-gaap:DepletionOfOilAndGasProperties',
                     'us-gaap:CostOfGoodsAndServicesSoldAmortization', 'us-gaap:AmortizationOfIntangibleAssets', 'us-gaap:AmortizationOfAcquisitionCosts', 'us-gaap:AmortizationOfDeferredSalesCommissions',
                     'us-gaap:FinanceLeaseRightOfUseAssetAmortization', 'us-gaap:AmortizationOfPowerContractsEmissionCredits', 'us-gaap:AmortizationOfNuclearFuelLease', 'us-gaap:AmortizationOfRegulatoryAsset',
                     'us-gaap:AmortizationOfAdvanceRoyalty', 'us-gaap:AmortizationOfDeferredPropertyTaxes', 'us-gaap:AmortizationOfRateDeferral', 'us-gaap:AmortizationOfDeferredHedgeGains',
                     'us-gaap:AmortizationAndDepreciationOfDecontaminatingAndDecommissioningAssets', 'us-gaap:OtherAmortizationOfDeferredCharges', 'us-gaap:AdjustmentForAmortization'},
    'deferred_income_tax': {'us-gaap:DeferredIncomeTaxExpenseBenefit', 'us-gaap:DeferredIncomeTaxesAndTaxCredits'},
    'share_based_compensation': {'us-gaap:EmployeeBenefitsAndShareBasedCompensationNoncash', 'us-gaap:ShareBasedCompensation', 'us-gaap:RestrictedStockExpense', 'us-gaap:StockOptionPlanExpense'},
    'change_working_capital': {'us-gaap:IncreaseDecreaseInOperatingCapital', 'us-gaap:IncreaseDecreaseInPayableForInvestmentPurchased', 'us-gaap:IncreaseDecreaseInReceivableForInvestmentSold', 'us-gaap:IncreaseDecreaseInProfessionalFeePayable',
         'us-gaap:IncreaseDecreaseInAdministrativeFeePayable', 'us-gaap:IncreaseDecreaseInDerivativeAssetsAndLiabilities', 'us-gaap:IncreaseDecreaseInRegulatoryAssetsAndLiabilities',
         'us-gaap:IncreaseDecreaseInIncomeTaxesPayableNetOfIncomeTaxesReceivable', 'us-gaap:IncreaseDecreaseInCommodityContractAssetsAndLiabilities', 'us-gaap:IncreaseDecreaseInOtherOperatingCapitalNet',
         'us-gaap:IncreaseDecreaseInOtherNoncurrentAssetsAndLiabilitiesNet', 'us-gaap:IncreaseDecreaseInOtherCurrentAssetsAndLiabilitiesNet', 'us-gaap:IncreaseDecreaseInManagementAndIncentiveFeesPayable',
         'us-gaap:IncreaseDecreaseInManagementFeePayable', 'us-gaap:IncreaseDecreaseInIncentiveFeePayable', 'us-gaap:IncreaseDecreaseInIncentiveFeePayableCapitalGainBased',
         'us-gaap:IncreaseDecreaseInIncentiveFeePayableIncomeBased', 'us-gaap:IncreaseDecreaseInOverUnderEnergyRecovery', 'us-gaap:IncreaseDecreaseInUnderEnergyRecovery', 'us-gaap:IncreaseDecreaseInOverEnergyRecovery',
         'us-gaap:IncreaseDecreaseInOperatingLiabilities', 'us-gaap:IncreaseDecreaseInOperatingLeaseLiability', 'us-gaap:IncreaseDecreaseInOptionPremiumContractsPayable',
         'us-gaap:IncreaseDecreaseInOutstandingChecksOperatingActivities', 'us-gaap:IncreaseDecreaseInRegulatoryClauseRevenue', 'us-gaap:IncreaseDecreaseInRegulatoryLiabilities',
         'us-gaap:IncreaseDecreaseInProductionParticipationPlanLiability', 'us-gaap:IncreaseDecreaseInAssetRetirementObligations', 'us-gaap:IncreaseDecreaseInRestructuringReserve', 'us-gaap:IncreaseDecreaseInSelfInsuranceReserve',
         'us-gaap:IncreaseDecreaseInDerivativeLiabilities', 'us-gaap:IncreaseDecreaseInDeferredRevenue', 'us-gaap:IncreaseDecreaseInContractWithCustomerLiability', 'us-gaap:IncreaseDecreaseInOtherOperatingLiabilities',
         'us-gaap:IncreaseDecreaseInOtherNoncurrentLiabilities', 'us-gaap:IncreaseDecreaseInOtherCurrentLiabilities', 'us-gaap:IncreaseDecreaseInAccruedTaxesPayable', 'us-gaap:IncreaseDecreaseInPropertyAndOtherTaxesPayable',
         'us-gaap:IncreaseDecreaseInAccruedIncomeTaxesPayable', 'us-gaap:IncreaseDecreaseInDeferredLiabilities', 'us-gaap:IncreaseDecreaseInOtherDeferredLiability', 'us-gaap:IncreaseDecreaseInDeferredCompensation',
         'us-gaap:IncreaseDecreaseInAccountsPayableAndAccruedLiabilities', 'us-gaap:IncreaseDecreaseInOtherAccountsPayableAndAccruedLiabilities', 'us-gaap:IncreaseDecreaseInAccruedLiabilities',
         'us-gaap:IncreaseDecreaseInOtherAccruedLiabilities', 'us-gaap:IncreaseDecreaseInInterestPayableNet', 'us-gaap:IncreaseDecreaseInEmployeeRelatedLiabilities', 'us-gaap:IncreaseDecreaseInOtherEmployeeRelatedLiabilities',
         'us-gaap:IncreaseDecreaseInPneumoconiosisBenefitObligationsNoncurrent', 'us-gaap:IncreaseDecreaseInPostemploymentObligations', 'us-gaap:IncreaseDecreaseInWorkersCompensationLiabilities',
         'us-gaap:IncreaseDecreaseInAccruedSalaries', 'us-gaap:IncreaseDecreaseInPensionAndPostretirementObligations', 'us-gaap:IncreaseDecreaseInPostretirementObligations', 'us-gaap:IncreaseDecreaseInPensionPlanObligations',
         'us-gaap:IncreaseDecreaseInAccountsPayable', 'us-gaap:IncreaseDecreaseInOtherAccountsPayable', 'us-gaap:IncreaseDecreaseInConstructionPayables', 'us-gaap:IncreaseDecreaseInRetainagePayable',
         'us-gaap:IncreaseDecreaseInRoyaltiesPayable', 'us-gaap:IncreaseDecreaseInNotesPayableCurrent', 'us-gaap:IncreaseDecreaseInAccountsPayableTrade', 'us-gaap:IncreaseDecreaseInDueToRelatedPartiesCurrent',
         'us-gaap:IncreaseDecreaseInDueToOtherRelatedPartiesCurrent', 'us-gaap:IncreaseDecreaseInDueToAffiliatesCurrent', 'us-gaap:IncreaseDecreaseInDueToEmployeesCurrent',
         'us-gaap:IncreaseDecreaseInDueToOfficersAndStockholdersCurrent', 'us-gaap:IncreaseDecreaseInNotesPayableRelatedPartiesCurrent', 'us-gaap:IncreaseDecreaseInAccountsPayableRelatedParties',
         'us-gaap:IncreaseDecreaseInOperatingAssets', 'us-gaap:IncreaseDecreaseInAllowanceForEquityFundsUsedDuringConstruction', 'us-gaap:IncreaseDecreaseInBalancingAccountUtility',
         'us-gaap:IncreaseDecreaseInOtherRegulatoryAssets', 'us-gaap:IncreaseDecreaseInGasImbalanceReceivable', 'us-gaap:IncreaseDecreaseInUnprovedOilAndGasProperty', 'us-gaap:IncreaseDecreaseInRecoverableRefundableGasCosts',
         'us-gaap:IncreaseDecreaseInEnergyTradingActivity', 'us-gaap:IncreaseDecreaseInAccruedCostOfOilAndGasReclamation', 'us-gaap:IncreaseDecreaseInRecoverablePropertyDamageCosts', 'us-gaap:IncreaseDecreaseInDerivativeAssets',
         'us-gaap:IncreaseDecreaseInMortgageLoansHeldForSale', 'us-gaap:IncreaseDecreaseInMaterialsAndSupplies', 'us-gaap:IncreaseDecreaseInContractWithCustomerAsset', 'us-gaap:IncreaseDecreaseInOtherOperatingAssets',
         'us-gaap:IncreaseDecreaseInOtherNoncurrentAssets', 'us-gaap:IncreaseDecreaseInOtherCurrentAssets', 'us-gaap:IncreaseDecreaseInPrepaidDeferredExpenseAndOtherAssets', 'us-gaap:IncreaseDecreaseInDeferredLeasingFees',
         'us-gaap:IncreaseDecreaseInDeferredCharges', 'us-gaap:IncreaseDecreaseInDeferredIncomeTaxes', 'us-gaap:IncreaseDecreaseInIntangibleAssetsCurrent', 'us-gaap:IncreaseDecreaseInAssetsHeldForSale',
         'us-gaap:IncreaseDecreaseInPrepaidExpensesOther', 'us-gaap:IncreaseDecreaseInPrepaidTaxes', 'us-gaap:IncreaseDecreaseInPrepaidInterest', 'us-gaap:IncreaseDecreaseInPrepaidSupplies',
         'us-gaap:IncreaseDecreaseInPrepaidAdvertising', 'us-gaap:IncreaseDecreaseInPrepaidRent', 'us-gaap:IncreaseDecreaseInPrepaidInsurance', 'us-gaap:IncreaseDecreaseInPrepaidRoyalties', 'us-gaap:IncreaseDecreaseInPrepaidExpense',
         'us-gaap:IncreaseDecreaseInDeferredFuelCosts', 'us-gaap:IncreaseDecreaseInDeferredElectricCost', 'us-gaap:IncreaseDecreaseInDeferredGasCost', 'us-gaap:IncreaseDecreaseInDepositOtherAssets',
         'us-gaap:IncreaseDecreaseInMarginDepositsOutstanding', 'us-gaap:IncreaseDecreaseInDepositsOutstanding', 'us-gaap:IncreaseDecreaseInFinancialInstrumentsUsedInOperatingActivities',
         'us-gaap:IncreaseDecreaseInOtherFinancialInstrumentsUsedInOperatingActivities', 'us-gaap:IncreaseDecreaseInRiskManagementAssetsAndLiabilities', 'us-gaap:IncreaseDecreaseInTradingSecurities',
         'us-gaap:IncreaseDecreaseInDebtSecuritiesTrading', 'us-gaap:IncreaseDecreaseInEquitySecuritiesFvNi', 'us-gaap:IncreaseDecreaseInInventories', 'us-gaap:IncreaseDecreaseInRetailRelatedInventories',
         'us-gaap:IncreaseDecreaseInRawMaterialsPackagingMaterialsAndSuppliesInventories', 'us-gaap:IncreaseDecreaseInInventoryForLongTermContractsOrPrograms', 'us-gaap:IncreaseDecreaseInFinishedGoodsAndWorkInProcessInventories',
         'us-gaap:IncreaseDecreaseInFuelInventories', 'us-gaap:IncreaseDecreaseInFossilFuelInventories', 'us-gaap:IncreaseDecreaseInOtherFossilFuelInventories', 'us-gaap:IncreaseDecreaseInCoalInventories',
         'us-gaap:IncreaseDecreaseInReceivables', 'us-gaap:IncreaseDecreaseInOtherReceivables', 'us-gaap:IncreaseDecreaseInAccountsReceivableFromSecuritization', 'us-gaap:IncreaseDecreaseInInsuranceSettlementsReceivable',
         'us-gaap:IncreaseDecreaseInFinanceReceivables', 'us-gaap:IncreaseDecreaseInAccruedInterestReceivableNet', 'us-gaap:IncreaseDecreaseInInterestsContinuedToBeHeldByTransferorCurrent',
         'us-gaap:IncreaseDecreaseInIncomeTaxesReceivable', 'us-gaap:IncreaseDecreaseInLeasingReceivables', 'us-gaap:IncreaseDecreaseInLongTermReceivablesCurrent', 'us-gaap:IncreaseDecreaseInNotesReceivableCurrent',
         'us-gaap:IncreaseDecreaseInAccountsAndOtherReceivables', 'us-gaap:IncreaseDecreaseInAccountsReceivable', 'us-gaap:IncreaseDecreaseInAccountsAndNotesReceivable', 'us-gaap:IncreaseDecreaseInDueFromRelatedPartiesCurrent',
         'us-gaap:IncreaseDecreaseInDueFromOtherRelatedPartiesCurrent', 'us-gaap:IncreaseDecreaseInDueFromAffiliatesCurrent', 'us-gaap:IncreaseDecreaseInDueFromOfficersAndStockholdersCurrent', 'us-gaap:IncreaseDecreaseInDueFromEmployeeCurrent',
         'us-gaap:IncreaseDecreaseInNotesReceivableRelatedPartiesCurrent', 'us-gaap:IncreaseDecreaseInAccountsReceivableRelatedParties'},
    # Investing cash flow
    'investing_cash_flow': {'us-gaap:NetCashProvidedByUsedInInvestingActivities', 'us-gaap:NetCashProvidedByUsedInInvestingActivitiesContinuingOperations', 'us-gaap:CashProvidedByUsedInInvestingActivitiesDiscontinuedOperations'},
    # todo new column
    'purc_sale_ppe': {'us-gaap:PaymentsForProceedsFromProductiveAssets', 'us-gaap:ProceedsFromSaleOfProductiveAssets', 'us-gaap:ProceedsFromSaleOfOtherProductiveAssets', 'us-gaap:ProceedsFromDisposalCryptoAsset', 'us-gaap:ProceedsFromSaleOfIntangibleAssets',
                      'us-gaap:ProceedsFromSaleOfPropertyPlantAndEquipment', 'us-gaap:ProceedsFromSaleOfOtherPropertyPlantAndEquipment', 'us-gaap:ProceedsFromSaleOfFurnitureAndFixtures', 'us-gaap:ProceedsFromSaleOfMachineryAndEquipment',
                      'us-gaap:ProceedsFromSaleOfBuildings', 'us-gaap:ProceedsFromSaleOfLandHeldForUse', 'us-gaap:PaymentsToAcquireProductiveAssets', 'us-gaap:PaymentsToAcquireOtherProductiveAssets', 'us-gaap:PaymentsToAcquireEquipmentOnLease', 
                      'us-gaap:PaymentForAcquisitionCryptoAsset', 'us-gaap:PaymentsToAcquireIntangibleAssets', 'us-gaap:PaymentsForSoftware', 'us-gaap:PaymentsToDevelopSoftware', 'us-gaap:PaymentsToAcquireSoftware', 'us-gaap:PaymentsToAcquirePropertyPlantAndEquipment',
                      'us-gaap:PaymentsToAcquireOtherPropertyPlantAndEquipment', 'us-gaap:PaymentsToAcquireFurnitureAndFixtures', 'us-gaap:PaymentsToAcquireMachineryAndEquipment', 'us-gaap:PaymentsToAcquireBuildings', 'us-gaap:PaymentsToAcquireLandHeldForUse'},
    # todo new column
    'purc_sale_investments': {'us-gaap:PaymentsForProceedsFromInvestments', 'us-gaap:ProceedsFromSaleMaturityAndCollectionsOfInvestments', 'us-gaap:ProceedsFromSaleOfRestrictedInvestments', 'us-gaap:ProceedsFromSaleOfInsuranceInvestments', 'us-gaap:ProceedsFromSaleOfOtherRealEstate',
                              'us-gaap:ProceedsFromSaleOfEquitySecuritiesFvNi', 'us-gaap:ProceedsFromSaleAndMaturityOfMarketableSecurities', 'us-gaap:ProceedsFromSaleAndMaturityOfOtherInvestments', 'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfOtherInvestments',
                              'us-gaap:ProceedsFromSaleOfOtherInvestments', 'us-gaap:ProceedsFromSaleAndCollectionOfReceivables', 'us-gaap:ProceedsFromCollectionOfAdvanceToAffiliate', 'us-gaap:ProceedsFromCollectionOfRetainedInterestInSecuritizedReceivablesCategorizedAsHeldToMaturity',
                              'us-gaap:ProceedsFromCollectionOfRetainedInterestInSecuritizedReceivablesCategorizedAsAvailableForSale', 'us-gaap:ProceedsFromSaleAndCollectionOfOtherReceivables', 'us-gaap:ProceedsFromCollectionOfOtherReceivables',
                              'us-gaap:ProceedsFromSaleOfOtherReceivables', 'us-gaap:ProceedsFromSaleAndCollectionOfNotesReceivable', 'us-gaap:ProceedsFromCollectionOfNotesReceivable', 'us-gaap:ProceedsFromSaleOfNotesReceivable',
                              'us-gaap:ProceedsFromSaleAndMaturityOfTradingSecuritiesHeldforinvestment', 'us-gaap:ProceedsFromMaturitiesRepaymentsAndCallsOfTradingSecuritiesHeldforinvestment', 'us-gaap:ProceedsFromSaleOfTradingSecuritiesHeldforinvestment',
                              'us-gaap:ProceedsFromSaleAndMaturityOfHeldToMaturitySecurities', 'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfHeldToMaturitySecurities', 'us-gaap:ProceedsFromSaleOfHeldToMaturitySecurities',
                              'us-gaap:ProceedsFromSaleAndMaturityOfAvailableForSaleSecurities', 'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities', 'us-gaap:ProceedsFromSaleOfAvailableForSaleSecuritiesDebt',
                              'us-gaap:ProceedsFromMaturitiesPrepaymentsAndCallsOfMortgageBackedSecuritiesMBS', 'us-gaap:ProceedsFromSaleOfMortgageBackedSecuritiesMBSCategorizedAsAvailableForSale', 'us-gaap:PaymentsToAcquireInvestments', 'us-gaap:PaymentsToAcquireOtherInvestments',
                              'us-gaap:PaymentsToAcquireRealEstateHeldForInvestment', 'us-gaap:PaymentsToAcquireMortgageBackedSecuritiesMBSCategorizedAsHeldToMaturity', 'us-gaap:PaymentsToAcquireMortgageBackedSecuritiesMBSCategorizedAsAvailableForSale',
                              'us-gaap:PaymentsToAcquireTradingSecuritiesHeldforinvestment', 'us-gaap:PaymentsToAcquireMarketableSecurities', 'us-gaap:PaymentsToAcquireHeldToMaturitySecurities', 'us-gaap:PaymentsToAcquireEquitySecuritiesFvNi',
                              'us-gaap:PaymentsToAcquireAvailableForSaleSecuritiesDebt', 'us-gaap:PaymentsToAcquireReceivables', 'us-gaap:PaymentsToAcquireOtherReceivables', 'us-gaap:PaymentsForAdvanceToAffiliate', 'us-gaap:PaymentsToAcquireRetainedInterestInSecuritizedReceivables',
                              'us-gaap:PaymentsToAcquireNotesReceivable', 'us-gaap:PaymentsToAcquireRestrictedInvestments', 'us-gaap:PaymentsToAcquireRestrictedCertificatesOfDeposit', 'us-gaap:PaymentsForProceedsFromOtherInvestingActivities'},
    'capital_expenditure': None, # Calculated
    # todo new column
    'purc_sale_businesses': {'us-gaap:PaymentsForProceedsFromBusinessesAndInterestInAffiliates', 'us-gaap:ProceedsFromDivestitureOfBusinessesAndInterestsInAffiliates', 'us-gaap:ProceedsFromDivestitureOfInterestInSubsidiariesAndAffiliates',
                            'us-gaap:ProceedsFromDivestitureOfInterestInJointVenture', 'us-gaap:ProceedsFromSaleOfEquityMethodInvestments', 'us-gaap:ProceedsFromDivestitureOfInterestInConsolidatedSubsidiaries', 'us-gaap:ProceedsFromDivestitureOfBusinessesNetOfCashDivested', 
                            'us-gaap:CashDivestedFromDeconsolidation', 'us-gaap:ProceedsFromDivestitureOfBusinesses', 'us-gaap:PaymentsToAcquireBusinessesAndInterestInAffiliates', 'us-gaap:PaymentsToAcquireInterestInSubsidiariesAndAffiliates', 'us-gaap:PaymentsToAcquireInterestInJointVenture',
                            'us-gaap:PaymentsToAcquireEquityMethodInvestments', 'us-gaap:PaymentsToAcquireAdditionalInterestInSubsidiaries', 'us-gaap:PaymentsToAcquireBusinessesNetOfCashAcquired', 'us-gaap:CashAcquiredFromAcquisition', 'us-gaap:OtherPaymentsToAcquireBusinesses', 
                            'us-gaap:PaymentsToAcquireBusinessesGross', 'us-gaap:PaymentsForProceedsFromPreviousAcquisition', 'us-gaap:PaymentsForPreviousAcquisition', 'us-gaap:ProceedsFromPreviousAcquisition'},
    # todo new column
    'loan_lease_activity': {'us-gaap:PaymentsForProceedsFromLoansAndLeases', 'us-gaap:PaymentsForProceedsFromOtherLoansAndLeases', 'us-gaap:ProceedsFromRecoveriesOfLoanPreviouslyChargedOff', 'us-gaap:PaymentsToAcquireLoansAndLeasesHeldForInvestment', 'us-gaap:PaymentsToAcquireOtherLoansAndLeasesHeldForInvestment',
                            'us-gaap:PaymentsToAcquireLeasesHeldForInvestment', 'us-gaap:PaymentsToAcquireLoansHeldForInvestment', 'us-gaap:PaymentsToAcquireLoansAndLeasesHeldForInvestmentCreditCardSecuritizations', 'us-gaap:ProceedsFromSaleOfLoansAndLeasesHeldForInvestment', 
                            'us-gaap:ProceedsOfOtherLoansAndLeasesHeldForInvestment', 'us-gaap:ProceedsFromLeasesHeldForInvestment', 'us-gaap:ProceedsFromSaleOfLoansHeldForInvestment', 'us-gaap:ProceedsFromSecuritizationsOfLoansHeldForInvestment', 'us-gaap:ProceedsFromSecuritizationsOfCreditCards',
                            'us-gaap:ProceedsFromSecuritizationsOfConsumerLoans', 'us-gaap:ProceedsFromLoanAndLeaseOriginationsAndPrincipalCollections1', 'us-gaap:ProceedsFromPrincipalRepaymentsOnLoansAndLeasesHeldForInvestment', 'us-gaap:ProceedsFromLoanOriginations1',
                            'us-gaap:ProceedsFromLeasePaymentSalesTypeAndDirectFinancingLeasesInvestingActivity', 'us-gaap:OperatingLeasePaymentsUse'},
    # Financing cash flow
    'financing_cash_flow': {'us-gaap:NetCashProvidedByUsedInFinancingActivities', 'us-gaap:NetCashProvidedByUsedInFinancingActivitiesContinuingOperationsAbstract', 'us-gaap:CashProvidedByUsedInFinancingActivitiesDiscontinuedOperations'},
    'dividends_paid': {'us-gaap:PaymentsOfDividends', 'us-gaap:PaymentsOfCapitalDistribution', 'us-gaap:PaymentsOfOrdinaryDividends', 'us-gaap:PaymentsOfDividendsMinorityInterest', 'us-gaap:PaymentsOfDividendsPreferredStockAndPreferenceStock', 'us-gaap:PaymentsOfDividendsCommonStock'},
    # todo new column
    'iss_pay_equity': {'us-gaap:ProceedsFromRepurchaseOfEquity', 'us-gaap:PaymentsForRepurchaseOfEquity', 'us-gaap:PaymentsForRepurchaseOfOtherEquity', 'us-gaap:PaymentsForRepurchaseOfWarrants', 'us-gaap:PaymentsForRepurchaseOfInitialPublicOffering',
                       'us-gaap:PaymentsForRepurchaseOfPrivatePlacement', 'us-gaap:PaymentsForRepurchaseOfConvertiblePreferredStock', 'us-gaap:PaymentsForRepurchaseOfPreferredStockAndPreferenceStock', 'us-gaap:PaymentsForRepurchaseOfCommonStock', 'us-gaap:ProceedsFromIssuanceOrSaleOfEquity',
                       'us-gaap:ProceedsFromOtherEquity', 'us-gaap:ProceedsFromContributedCapital', 'us-gaap:ProceedsFromWarrantExercises', 'us-gaap:ProceedsFromStockPlans', 'us-gaap:ProceedsFromStockOptionsExercised', 'us-gaap:ProceedsFromIssuanceInitialPublicOffering', 'us-gaap:ProceedsFromIssuanceOfPrivatePlacement',
                       'us-gaap:ProceedsFromIssuanceOfCommonStockDividendReinvestmentPlan', 'us-gaap:ProceedsFromIssuanceOfConvertiblePreferredStock', 'us-gaap:ProceedsFromSaleOfTreasuryStock', 'us-gaap:ProceedsFromIssuanceOfCommonStock', 'us-gaap:ProceedsFromIssuanceOfPreferredStockPreferenceStockAndWarrants',
                       'us-gaap:ProceedsFromIssuanceOfWarrants', 'us-gaap:ProceedsFromIssuanceOfPreferredStockAndPreferenceStock'},
    # todo new column
    'iss_pay_debt': {'us-gaap:RepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess', 'us-gaap:ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess', 'us-gaap:AdditionsToContractHoldersFunds', 'us-gaap:RepaymentsOfLongTermLinesOfCredit', 'us-gaap:ProceedsFromRepaymentsOfDebtMaturingInMoreThanThreeMonths',
                     'us-gaap:ProceedsFromRepaymentsOfLongTermDebtAndCapitalSecurities', 'us-gaap:ProceedsFromIssuanceOfSubordinatedLongTermDebt', 'us-gaap:ProceedsFromRepaymentsOfOtherDebt', 'us-gaap:ProceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet', 'us-gaap:NetChangeContractHoldersFunds',
                     'us-gaap:ProceedsFromOtherShortTermDebt', 'us-gaap:RepaymentsOfMandatoryRedeemableCapitalSecurities', 'us-gaap:ProceedsFromIssuanceOfSeniorLongTermDebt', 'us-gaap:ProceedsFromShortTermDebtMaturingInMoreThanThreeMonths', 'us-gaap:ProceedsFromRepaymentsOfBankOverdrafts',
                     'us-gaap:ProceedsFromDebtNetOfIssuanceCosts', 'us-gaap:MaturitiesOfSubordinatedDebt', 'us-gaap:RepaymentsOfOtherDebt', 'us-gaap:ProceedsFromIssuanceOfFinancialServicesObligations', 'us-gaap:RepaymentsOfCommercialPaper', 'us-gaap:RepaymentsOfAccountsReceivableSecuritization',
                     'us-gaap:ProceedsFromAccountsReceivableSecuritization', 'us-gaap:EarlyRepaymentOfSeniorDebt', 'us-gaap:ProceedsFromIssuanceOfOtherLongTermDebt', 'us-gaap:RepaymentsOfOtherShortTermDebt', 'us-gaap:RepaymentsOfConvertibleDebt', 'us-gaap:ProceedsFromRepaymentsOfShortTermDebt',
                     'us-gaap:RepaymentsOfDebtMaturingInMoreThanThreeMonths', 'us-gaap:RepaymentsOfLongTermDebtAndCapitalSecurities', 'us-gaap:RepaymentsOfOtherLongTermDebt', 'us-gaap:RepaymentsOfBankDebt', 'us-gaap:ProceedsFromOtherDebt', 'us-gaap:IncreaseDecreaseInBookOverdrafts',
                     'us-gaap:IncreaseDecreaseInSecuritiesLendingPayable', 'us-gaap:RepaymentsOfLongTermDebt', 'us-gaap:ProceedsFromIssuanceOfMandatoryRedeemableCapitalSecurities', 'us-gaap:ProceedsFromRepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths',
                     'us-gaap:RepaymentsOfShortTermDebtMaturingInMoreThanThreeMonths', 'us-gaap:ProceedsFromShortTermDebt', 'us-gaap:ProceedsFromSubordinatedShortTermDebt', 'us-gaap:ProceedsFromConvertibleDebt', 'us-gaap:RepaymentsOfShortTermDebt', 'us-gaap:RepaymentsOfLongtermLoansFromVendors',
                     'us-gaap:RepaymentsOfSubordinatedShortTermDebt', 'us-gaap:RepaymentsOfDebt', 'us-gaap:RepaymentsOfSeniorDebt', 'us-gaap:IncreaseDecreaseInFederalFundsPurchased', 'us-gaap:RepaymentsOfLinesOfCredit', 'us-gaap:RepaymentsOfNotesPayable', 'us-gaap:ProceedsFromBankDebt',
                     'us-gaap:ProceedsFromLinesOfCredit', 'us-gaap:RepaymentsOfRelatedPartyDebt', 'us-gaap:ProceedsFromNotesPayable', 'us-gaap:ProceedsFromLongTermLinesOfCredit', 'us-gaap:ProceedsFromRepaymentsOfAccountsReceivableSecuritization', 'us-gaap:ProceedsFromRepaymentsOfDebt',
                     'us-gaap:ProceedsFromIssuanceOfLongTermDebt', 'us-gaap:ProceedsFromDebtMaturingInMoreThanThreeMonths', 'us-gaap:ProceedsFromShortTermDebtMaturingInThreeMonthsOrLess', 'us-gaap:ProceedsFromRelatedPartyDebt', 'us-gaap:WithdrawalFromContractHoldersFunds',
                     'us-gaap:IncreaseDecreaseInFederalFundsPurchasedAndSecuritiesSoldUnderAgreementsToRepurchaseNet', 'us-gaap:ProceedsFromRepaymentsOfLinesOfCredit', 'us-gaap:ProceedsFromIssuanceOfDebt', 'us-gaap:ProceedsFromRepaymentsOfCommercialPaper', 'us-gaap:ProceedsFromIssuanceOfCommercialPaper',
                     'us-gaap:RepaymentsOfFederalHomeLoanBankBorrowings', 'us-gaap:ProceedsFromFederalHomeLoanBankBorrowings', 'us-gaap:MaturitiesOfSeniorDebt', 'us-gaap:RepaymentsOfDebtAndCapitalLeaseObligations', 'us-gaap:IncreaseDecreaseInOutstandingChecksFinancingActivities',
                     'us-gaap:ProceedsFromIssuanceOfMediumTermNotes', 'us-gaap:RepaymentsOfMediumTermNotes', 'us-gaap:FinanceLeasePrincipalPayments', 'us-gaap:ProceedsFromPaymentsForInSecuritiesSoldUnderAgreementsToRepurchase'},
    'debt_issued': None, # Calculated
    'debt_repayment': None, # Calculated
    # Additional fields
    'free_cash_flow': None, # Calculated
    'start_cash_balance': {'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents', # todo rename column
                               'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations',
                               'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsDisposalGroupIncludingDisc'},
    'end_cash_balance': {'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents',
                         'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents_1',
                         'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations',
                         'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsIncludingDisposalGroupAndDiscontinuedOperations:1'
                         'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsDisposalGroupIncludingDisc'},
    'inc_dec_cash': {'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffect',
                     'us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseExcludingExchangeRateEffect'}
}


balance_sheet_ifrs = ['ifrs-full:CurrentAssets',
                      'ifrs-full:CashAndCashEquivalents', 'ifrs-full:Cash',
                      'ifrs-full:RestrictedCashAndCashEquivalents',
                      'ifrs-full:TradeAndOtherCurrentReceivables',
                      'ifrs-full:Inventories',
                      #Non Current Asset
                      'ifrs-full:NoncurrentAssets',
                      'ifrs-full:PropertyPlantAndEquipment',
                      'ifrs-full:IntangibleAssetsOtherThanGoodwill',
                      'ifrs-full:Goodwill',
                      'ifrs-full:DeferredTaxAssets',
                      # Equity
                      'ifrs-full:Equity',
                      'ifrs-full:IssuedCapital',
                      'ifrs-full:AdditionalPaidinCapital',
                      'ifrs-full:RetainedEarnings',
                      # Liabilities
                      'ifrs-full:Liabilities',
                      'ifrs-full:TradeAndOtherCurrentPayables',
                      'ifrs-full:ShorttermBorrowings',
                      'ifrs-full:CurrentLeaseLiabilities',
                      'ifrs-full:CurrentTaxLiabilitiesCurrent',
                      # Non Current Liabilities
                      'ifrs-full:NoncurrentLiabilities',
                      'ifrs-full:LongtermBorrowings',
                      'ifrs-full:NoncurrentLeaseLiabilities',
                      'ifrs-full:DeferredIncomeClassifiedAsNoncurrent'
                      ]


income_statement_ifrs = ['ifrs-full:RevenueFromContractsWithCustomers', 'ifrs-full:CostOfSales', 'ifrs-full:GrossProfit',
                         'ifrs-full:OtherIncome', 'ifrs-full:GeneralAndAdministrativeExpense', 'ifrs-full:SellingExpense',
                         'ifrs-full:ProfitLossFromOperatingActivities', 'ifrs-full:InterestRevenueExpense', 'ifrs-full:ProfitLossBeforeTax', 'ifrs-full:IncomeTaxExpenseContinuingOperations',
                         'ifrs-full:ProfitLossFromContinuingOperations', 'ifrs-full:ProfitLoss']
xbrl_tags = {
    'us-gaap': {'BalanceSheet': balance_sheet_gaap, 'IncomeStatement': income_statement_gaap, 'CashFlowStatement': cash_flow_gaap},
    'ifrs-full': {'BalanceSheet': balance_sheet_ifrs, 'IncomeStatement': income_statement_ifrs, 'CashFlowStatement': None}
}